@startuml
'https://plantuml.com/activity-diagram-beta

start
:Trykk Admin;
:Logg inn med brukernavn og passord;
:Trykk på "Oversikt over omvisninger";
:Trykk på valgt omvisning;
if (vil redigere?) is (Ja) then
  :Trykk på "Redigere omvisning";
  if (endringer skal lagres?) is (Ja) then
    :Trykk på Lagre endring;
  else (Nei)
  :Trykk "Tilbake";
  :Se "Oversikt over omvisninger";
  endif
else (Nei)
:Trykk "Tilbake"";
endif
:Trykk "Logg ut";
stop

@enduml
