@startuml
'https://plantuml.com/activity-diagram-beta

start
:Trykk på "Lag ny bruker";
:Legg til nødvendig informasjon;
:Trykk opprett bruker;
if (bruker opprettet) then (ok)
  :Trykk "Lagre";
else (nei)
 :Feilmelding;
  endif

stop

@enduml
