@startuml
'https://plantuml.com/activity-diagram-beta

start
:Trykker "Lag ny bruker";
:Legger til nødvendig informasjon;
:Trykker "Opprett bruker";
if (bruker opprettelse vellykket?) then (Ja)
    :Brukerkonto lagres i databasen;
    :Sendes til innlogging skjerm;
else (Nei)
    #pink:Feilmelding;
endif

stop
@enduml
