@startuml
'https://plantuml.com/activity-diagram-beta
start
:Legge til omvisning;
if (IfGuideClicksLeggTilOmvisning) is (yes) then
  :OmvisningOpprettet;
  :TourConfirmedPage;
else (no)
  :OpprettelsenFeilet;
  :ErrorMessage;
endif
:LoggUt;
stop
@enduml
