@startuml
skinparam linetype ortho

entity users {
    *id: integer <<Generated>>
    --
    *name: varchar(50)
}

entity tours {
    *id: integer <<Generated>>
    --
    *user_id: integer <<FK>>
    *title: varchar(100)

    *meet_point: varchar(100)
}

entity tour_times {
    *id: integer <<Generated>>
    --
    *tour_id: integer <<FK>>
    *date: date
    *begin_time: time
}

entity bookings {
    *tourTime_id: integer <<FK>>
    *user_id: integer <<FK>>
    --
    *adult_count: integer
    *child_count: integer
    *infant_count: integer
    *cost: integer
}

users ||--o{ tours
tours ||--o{ tour_times
bookings }o--|| tour_times
bookings }o--|| users

@enduml